### PR TITLE
Fixed the Quotes Issue

### LINKED ISSUE #402: Motivational Quotes
image

### PR DESCRIPTION
**Pull request by itz-rj-here**
## Description
Replaced the ZenQuotes API with the DummyJSON API to fix the issue of rate limits and ensure dynamic quote functionality works reliably. The new API provides random quotes without requiring an API key, ensuring seamless updates on each load.

## Related Issues
Closes #402 

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by itz-rj-here** [comment]
@prem-k-r

**Comment by itz-rj-here** [comment]
image
I am having this issue.

**Comment by prem-k-r** [comment]
I can check in like half an hour

**Comment by prem-k-r** [comment]
> image I am having this issue.

We can limit fetching to character count x to y.. check in zenquotes one

**Comment by itz-rj-here** [comment]
Now which Quotes are too big they will show like this
image

**Comment by itz-rj-here** [comment]
> > image I am having this issue.
> 
> We can limit fetching to character count x to y.. check in zenquotes one

Fixed it alr.

**Comment by prem-k-r** [comment]
Instead of truncating, we can filter prior to showing

**Comment by Thunder-Blaze** [comment]
@itz-rj-here lemme try ig if I can fix this

**Comment by itz-rj-here** [comment]
@prem-k-r please review this

**Comment by Thunder-Blaze** [comment]
Ah the local storage part is not done yet.
I'm in online class rn
I'll make a pr in an hour

**Comment by itz-rj-here** [comment]
I will be here. Just mention me, i will be here.

**Comment by itz-rj-here** [comment]
@prem-k-r @Thunder-Blaze Someone have to review this pr now :)

**Comment by prem-k-r** [comment]
I am checking in few mins

**Review by Thunder-Blaze — APPROVED** [review]

**Comment by prem-k-r** [comment]
@Thunder-Blaze it is fetching every 5 min rn, did u missed a 0? coz u wrote 50 min.. or wrote extra zero here
I'm not sure what time to keep

**Comment by prem-k-r** [comment]
dont merge yet, i'm changing some stuff

**Comment by Thunder-Blaze** [comment]
> @Thunder-Blaze it is fetching every 5 min rn, did u missed a 0? coz u wrote 50 min.. or wrote extra zero here I'm not sure what time to keep

Huh 🥲, please add one more 0 in the changes you are doing

**Comment by prem-k-r** [comment]
I cant raise pr, it's saying something Protected branch

**Comment by prem-k-r** [comment]
image

**Comment by Thunder-Blaze** [comment]
Ok I'll try
Did you changed any other things except the 0 ?

**Comment by prem-k-r** [comment]
```
const apiUrl = "https://dummyjson.com/quotes?limit=50";
const quotesContainer = document.querySelector('.quotesContainer');
const authorName = document.querySelector('.authorName span');

// Set character limits for quotes
const MIN_QUOTE_LENGTH = 75;
const MAX_QUOTE_LENGTH = 125;
const QUOTE_REFRESH_INTERVAL = 5 * 60 * 1000; // 5 minutes in milliseconds

// Default quotes for offline or error scenarios
const defaultQuotes = [
    { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "Keep your face always toward the sunshine and shadows will fall behind you.", author: "Walt Whitman" }
];

async function fetchAndStoreQuotes() {
    try {
        const randnum = Math.floor(Math.random() * 28) * 50;
        const response = await fetch(`${apiUrl}&skip=${randnum}`);
        if (!response.ok) throw new Error(`HTTP error! Status: ${response.status}`);
        const data = await response.json();

        // Extract and filter quotes from the response
        const filteredQuotes = data.quotes.filter(quote =>
            quote.quote.length >= MIN_QUOTE_LENGTH && quote.quote.length <= MAX_QUOTE_LENGTH
        );

        // Save the filtered quotes to localStorage
        if (filteredQuotes.length > 0) {
            localStorage.setItem("allQuotes", JSON.stringify(filteredQuotes));
            localStorage.setItem("quoteIndex", "0"); // Reset the index
        }
    } catch (error) {
        console.error("Error fetching quotes:", error);
        // Use default quotes in case of an error
        localStorage.setItem("allQuotes", JSON.stringify(defaultQuotes));
        localStorage.setItem("quoteIndex", "0"); // Reset the index
    }
}

function displayQuote(quote) {
    quotesContainer.textContent = `"${quote.quote}"`;
    authorName.textContent = quote.author;
}

function displayNextQuote() {
    const storedQuotes = JSON.parse(localStorage.getItem("allQuotes") || "[]");
    let quoteIndex = parseInt(localStorage.getItem("quoteIndex") || "0", 10);

    // Check if we need to fetch new quotes
    if (storedQuotes.length === 0 || quoteIndex >= storedQuotes.length) {
        fetchAndStoreQuotes().then(() => displayNextQuote());
        return;
    }

    // Display the current quote
    const quoteToShow = storedQuotes[quoteIndex];
    displayQuote(quoteToShow);

    // Remove the displayed quote from the list in localStorage
    storedQuotes.splice(quoteIndex, 1); // Remove the current quote

    // Update the index for the next quote
    localStorage.setItem("allQuotes", JSON.stringify(storedQuotes));
    quoteIndex++;
    localStorage.setItem("quoteIndex", quoteIndex.toString());
}

function refreshQuoteIfNeeded() {
    const lastUpdated = parseInt(localStorage.getItem("lastQuoteUpdate") || "0", 10);
    const now = Date.now();

    // Check if 5 minutes have passed since the last update
    if (now - lastUpdated >= QUOTE_REFRESH_INTERVAL) {
        displayNextQuote();
        localStorage.setItem("lastQuoteUpdate", now.toString());
    }
}

// Initial load
if (localStorage.getItem("motivationalQuotesVisible") !== "false") {
    const storedQuotes = JSON.parse(localStorage.getItem("allQuotes") || "[]");

    if (storedQuotes.length === 0) {
        fetchAndStoreQuotes().then(() => {
            localStorage.setItem("lastQuoteUpdate", Date.now().toString());
            displayNextQuote(); // Display the first quote immediately
        });
    } else {
        // Display the first quote immediately on reload
        const quoteIndex = parseInt(localStorage.getItem("quoteIndex") || "0", 10);
        const quoteToShow = storedQuotes[quoteIndex];
        displayQuote(quoteToShow);

        refreshQuoteIfNeeded(); // Set up the 5-minute refresh logic
    }

    // Set an interval to refresh the quote every minute
    setInterval(refreshQuoteIfNeeded, 60 * 1000); // Check every minute
}

```

and `authorName` spelling correction in html and css

**Comment by Thunder-Blaze** [comment]
umm we keep 5 min or 50 min for quotes ?
image
you said to keep em for 1 hour I think ?

**Comment by prem-k-r** [comment]
I didnt changed from 5 min, since they are fetching from local storage after fetching directly from api once
we can change it.. idk what time to refresh

there might be errors in code, please review too.. most part chatGPTed

**Comment by Thunder-Blaze** [comment]
Oh finally understood the code,
so we are fetching and then storing them
everytime they display for 5 min, we remove them from local storage
and we are refetch the quotes

**Comment by itz-rj-here** [comment]
> image

Uhh. The thing is completely right. If you click the propose changes it will work perfectly. The branch is protected for you and me only. So that XengShi is the only one who can merge the pr with bypass rules.

**Comment by itz-rj-here** [comment]
If thre rules wasn’t setuped the changes will directly effect the main branch thats way i gaved him the protected branch rules.

**Comment by prem-k-r** [comment]
> > image
> 
> Uhh. The thing is completely right. If you click the propose changes it will work perfectly. The branch is protected for you and me only. So that XengShi is the only one who can merge the pr with bypass rules.

yeah i clicked on propose change, it shows error in top red box.. 
I'm trying to pull PR in your branch though?

**Comment by itz-rj-here** [comment]
> > > image
> > 
> > 
> > Uhh. The thing is completely right. If you click the propose changes it will work perfectly. The branch is protected for you and me only. So that XengShi is the only one who can merge the pr with bypass rules.
> 
> yeah i clicked on propose change, it shows error in top red box.. I'm trying to pull PR in your branch though?

Ok will check that.

**Review by Thunder-Blaze — APPROVED** [review]
The first quote changes without a timeout but I don't think it's causing any problem

**Review by prem-k-r — APPROVED** [review]
Working fine.
I dont understand some of the parts thoroughly though :p

**Comment by itz-rj-here** [comment]
@XengShi now listen carefully. Click the tickmark of the bypass rules and then click the bypass mergre pr.
Also you can test the changes first and then merge it.

**Comment by prem-k-r** [comment]
btw this api also giving some odd quotes, and some religious ones too

**Comment by itz-rj-here** [comment]
> btw this api also giving some odd quotes, and some religious ones too

Uhhmm. Wait then let me research on it more.

**Comment by itz-rj-here** [comment]
I have to sleep now. @prem-k-r if you can manage you can see this https://github.com/Ovi/DummyJSON

**Comment by prem-k-r** [comment]
dont know why but Im suddenly seeing this error
image

logging off, will see later

**Comment by prem-k-r** [comment]
Solving one bug gives rise to another

you guys check it please
```
const apiUrl = "https://dummyjson.com/quotes?limit=50";
const quotesContainer = document.querySelector('.quotesContainer');
const authorName = document.querySelector('.authorName span');

// Set character limits for quotes
const MIN_QUOTE_LENGTH = 75;
const MAX_QUOTE_LENGTH = 125;
const QUOTE_REFRESH_INTERVAL = 10 * 60 * 1000;; // 10 minutes in milliseconds

// Default quotes for offline or error scenarios
const defaultQuotes = [
    { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "Keep your face always toward the sunshine and shadows will fall behind you.", author: "Walt Whitman" }
];

// Cache variables
let cachedQuotes = [];
let quoteIndex = 0;

async function fetchAndStoreQuotes() {
    try {
        const randnum = Math.floor(Math.random() * 28) * 50;
        const response = await fetch(`${apiUrl}&skip=${randnum}`);
        if (!response.ok) throw new Error(`HTTP error! Status: ${response.status}`);
        const data = await response.json();

        // Extract and filter quotes from the response
        const filteredQuotes = data.quotes.filter(quote =>
            quote.quote.length >= MIN_QUOTE_LENGTH && quote.quote.length <= MAX_QUOTE_LENGTH
        );

        if (filteredQuotes.length > 0) {
            localStorage.setItem("allQuotes", JSON.stringify(filteredQuotes));
            cachedQuotes = filteredQuotes; // Update cache
            quoteIndex = 0; // Reset index in cache
        }
    } catch (error) {
        console.error("Error fetching quotes:", error);
        // Use default quotes in case of an error
        localStorage.setItem("allQuotes", JSON.stringify(defaultQuotes));
        cachedQuotes = defaultQuotes; // Update cache
        quoteIndex = 0; // Reset index in cache
    }

    // After fetching, ensure lastQuoteUpdate is set
    localStorage.setItem("lastQuoteUpdate", Date.now().toString());
}

function displayQuote(quote) {
    if (!quote || !quote.quote || !quote.author) {
        const fallback = defaultQuotes[0];
        quotesContainer.textContent = `"${fallback.quote}"`;
        authorName.textContent = fallback.author;
        return;
    }
    quotesContainer.textContent = `"${quote.quote}"`;
    authorName.textContent = quote.author;
}

function displayNextQuote() {
    // If cache is empty, populate it from localStorage
    if (cachedQuotes.length === 0) {
        cachedQuotes = JSON.parse(localStorage.getItem("allQuotes") || "[]");
    }

    // Check if we need to fetch new quotes
    if (cachedQuotes.length === 0) {
        fetchAndStoreQuotes().then(() => displayNextQuote());
        return;
    }

    // Display the current quote
    const quoteToShow = cachedQuotes[quoteIndex]; // Use the correct index
    if (quoteToShow) {
        displayQuote(quoteToShow);
    }

    // Remove the displayed quote from the list
    cachedQuotes.splice(quoteIndex, 1); // Remove the current quote
    localStorage.setItem("allQuotes", JSON.stringify(cachedQuotes)); // Update localStorage

    // Update the index
    quoteIndex = Math.max(quoteIndex, cachedQuotes.length); // Prevent index overflow

    // Fetch new quotes if none are left
    if (cachedQuotes.length === 0) {
        fetchAndStoreQuotes();
    }
}

function refreshQuoteIfNeeded() {
    const lastUpdated = parseInt(localStorage.getItem("lastQuoteUpdate") || "0", 10);
    const now = Date.now();

    if (now - lastUpdated >= QUOTE_REFRESH_INTERVAL) {
        displayNextQuote();
        localStorage.setItem("lastQuoteUpdate", now.toString()); // Update the timestamp immediately
    }
}

// Initial load
if (localStorage.getItem("motivationalQuotesVisible") !== "false") {
    cachedQuotes = JSON.parse(localStorage.getItem("allQuotes") || "[]"); // Populate cache from localStorage

    if (cachedQuotes.length === 0) {
        fetchAndStoreQuotes().then(() => {
            displayNextQuote(); // Display immediately after fetching
        });
    } else {
        displayNextQuote(); // Display the first quote
        refreshQuoteIfNeeded(); // Check for 10-minute refresh immediately
    }

    setInterval(refreshQuoteIfNeeded, 60 * 1000); // Check every minute
}

```


here 10 min retention is not working

**Comment by itz-rj-here** [comment]
@prem-k-r it's not working.
image

**Comment by prem-k-r** [comment]
> Solving one bug gives rise to another
> 
> you guys check it please
> ...
> 
> here 10 min retention is not working

some stuff still need to be fix

as for author name, most probably you haven't change autherName to authorName in html and css in your local system

**Comment by itz-rj-here** [comment]
> > Solving one bug gives rise to another
> > 
> > you guys check it please
> > ...
> > 
> > here 10 min retention is not working
> 
> some stuff still need to be fix
> 
> as for author name, most probably you haven't change autherName to authorName in html and css in your local system
> 
> 

Then you do for now. I will check later.

**Comment by itz-rj-here** [comment]
You also have the power to edit pr files.

**Comment by Thunder-Blaze** [comment]
Hmm I think I found a way to fix this, I'll try and make a pr in the next half hour

**Comment by prem-k-r** [comment]
> Hmm I think I found a way to fix this, I'll try and make a pr in the next half hour

please also add 
```
{ quote: "Since light travels faster than sound, some people appear bright until you hear them speak.", author: "Alan Dundes" },
```
as asked by xengshi

**Comment by prem-k-r** [comment]
> You also have the power to edit pr files.

I checked, i'm unable to edit your files.
I can't even pull(not merge) PR directly now to any of your branch or Xengshi's..
see if you can.. might be same with you

maybe some extra unnecessary rule added?

**Comment by Thunder-Blaze** [comment]
> > Hmm I think I found a way to fix this, I'll try and make a pr in the next half hour
> 
> please also add
> 
> ```
> { quote: "Since light travels faster than sound, some people appear bright until you hear them speak.", author: "Alan Dundes" },
> ```
> 
> as asked by xengshi

sure am on it

**Comment by itz-rj-here** [comment]
Guys im back. What is the status?

**Comment by Thunder-Blaze** [comment]
It's working for me
am checking for errors
I'll make a PR soon ig

**Comment by Thunder-Blaze** [comment]
@prem-k-r you can check the pr, it's working for me (this time tested with caution 😅 but still check if there are any errors)
https://github.com/itz-rj-here/materialYouNewTab/pull/23

**Comment by prem-k-r** [comment]
some edge cases
image
image

**Comment by XengShi** [comment]
> some edge cases
> image
> image
> 



I think we need this design

**Comment by itz-rj-here** [comment]
> > some edge cases
> > image
> > image
> 
> 
> 
> I think we need this design

It doesn't looks good :(

**Comment by Thunder-Blaze** [comment]
> some edge cases image image

Edge cases will occurr imo unless we use a monospace font
or either we lower the limit

**Comment by prem-k-r** [comment]
we can modify pre filtering condition, character limit on quote+authorname

**Comment by itz-rj-here** [comment]
> we can modify pre filtering condition, character limit on quote+authorname

You guys work in this lemme check the firefox issue.

**Comment by Thunder-Blaze** [comment]
> we can modify pre filtering condition, character limit on quote+authorname

I think that'll also produce exceptions sometimes
consider a quote+authorname with too many i or similar lower width characters
while another quote with too many m or w or similar higher width characters

**Comment by Thunder-Blaze** [comment]
@prem-k-r so what to do should I try limiting author+quote ? or try monospace fonts (Though they don't look very good when used for quotes)

**Comment by prem-k-r** [comment]
I would suggest limiting author+quote

**Comment by prem-k-r** [comment]
Btw @XengShi do we want quotation around quote?

**Comment by XengShi** [comment]
> Btw @XengShi do we want quotation around quote? 
> 

Nope!

**Comment by Thunder-Blaze** [comment]
> I would suggest limiting author+quote

Ok I'll make the changes then we can test that

**Comment by prem-k-r** [comment]
> > Btw @XengShi do we want quotation around quote?
> 
> Nope!

@Thunder-Blaze please remove “ and ” too

**Comment by prem-k-r** [comment]
> @prem-k-r you can check the pr, it's working for me (this time tested with caution 😅 but still check if there are any errors) [itz-rj-here#23](https://github.com/itz-rj-here/materialYouNewTab/pull/23)

seems to be working as expected

**Comment by prem-k-r** [comment]
image
guys we should change this alt text?

**Comment by Thunder-Blaze** [comment]
> > > Btw @XengShi do we want quotation around quote?
> > 
> > 
> > Nope!
> 
> @Thunder-Blaze please remove “ and ” too

From where ?

**Comment by prem-k-r** [comment]
> > > > Btw @XengShi do we want quotation around quote?
> > > 
> > > 
> > > Nope!
> > 
> > 
> > @Thunder-Blaze please remove “ and ” too
> 
> From where ?

from 
"Think beyond horizon."
to just
Think beyond horizon.

**Comment by prem-k-r** [comment]
Quotes are being displayed alongwith quotation marks

**Comment by itz-rj-here** [comment]
> > > > Btw @XengShi do we want quotation around quote?
> > > 
> > > 
> > > Nope!
> > 
> > 
> > @Thunder-Blaze please remove “ and ” too
> 
> From where ?

Bro the quotation mark "" this thing

**Comment by prem-k-r** [comment]
nvm, you have already removed them

**Comment by Thunder-Blaze** [comment]
wait wait wait Didn't I already fix this
image
It's showing like this for me

**Comment by Thunder-Blaze** [comment]
> image guys we should change this alt text?

I changed it in the PR in which I switched to author+quote length filtering

**Comment by prem-k-r** [comment]
Thanks @Thunder-Blaze :)

**Review by prem-k-r — APPROVED** [review]

**Review by Thunder-Blaze — APPROVED** [review]

**Comment by Thunder-Blaze** [comment]
> Thanks @Thunder-Blaze :)

Glad to be of help :)

**Comment by prem-k-r** [comment]
image
man.. logging off

**Comment by Thunder-Blaze** [comment]
> image man.. logging off

Lmao the ... And many l caused it
Monospace font or either @itz-rj-here decrease the max length to 150 in web editor, I can't make a pr again as I also closed the pc 😅

File: quotes.js [hunk 1]
```diff
@@ -1,35 +1,121 @@
...
+const authorName = document.querySelector('.authorName span');
 
-async function fetchAndDisplayQuote() {
-    try {
-        const response = await fetch(apiUrl);
-        const data = await response.json();
-        const quotes = JSON.parse(data.contents);
+// Set character limits for quotes
+const MIN_QUOTE_LENGTH = 100;
+const MAX_QUOTE_LENGTH = 160;
```
Comment (prem-k-r) [inline quotes.js:7]: 145

File: quotes.js [hunk 2]
```diff
@@ -3,8 +3,8 @@ const quotesContainer = document.querySelector('.quotesContainer');
 const authorName = document.querySelector('.authorName span');
 
 // Set character limits for quotes
-const MIN_QUOTE_LENGTH = 75;
-const MAX_QUOTE_LENGTH = 125;
+const MIN_QUOTE_LENGTH = 100;
```
Comment (prem-k-r) [inline quotes.js:6]: 90

**Comment by prem-k-r** [comment]
@itz-rj-here

File: quotes.js [hunk 3]
```diff
@@ -1,35 +1,121 @@
...
 
-async function fetchAndDisplayQuote() {
-    try {
-        const response = await fetch(apiUrl);
-        const data = await response.json();
-        const quotes = JSON.parse(data.contents);
+// Set character limits for quotes
+const MIN_QUOTE_LENGTH = 100;
+const MAX_QUOTE_LENGTH = 160;
+const QUOTE_REFRESH_INTERVAL = 10 * 60 * 1000;; // 10 minutes in milliseconds
```
Comment (prem-k-r) [inline quotes.js:8]: extra semicolon

File: quotes.js (hunk 1 above)
Comment (itz-rj-here) [reply quotes.js:7]: Bruh im outside 🗿

Comment (itz-rj-here) [reply quotes.js:7]: Bruh im outside 🗿

File: quotes.js [hunk 4]
```diff
@@ -1,35 +1,121 @@
...
+        cachedQuotes.splice(0, 1); // Remove the current quote
+        const quoteToShow = cachedQuotes[0]; // Use the correct index
+        if (quoteToShow) {
+            displayQuote(quoteToShow);
+        }
+        localStorage.setItem("allQuotes", JSON.stringify(cachedQuotes)); // Update localStorage
+        // After removing, ensure lastQuoteUpdate is set
+        localStorage.setItem("lastQuoteUpdate", Date.now().toString());
+    }
+    console.log(cachedQuotes);
```
Comment (prem-k-r) [inline quotes.js:90]: delete log

File: quotes.js (hunk 1 above)
Comment (prem-k-r) [reply quotes.js:7]: nw.. pls do it later

**Comment by itz-rj-here** [comment]
Did the changes through phone 😗

**Review by prem-k-r — DISMISSED** [review]

**Comment by Thunder-Blaze** [comment]
Thanks @itz-rj-here :)

**Comment by itz-rj-here** [comment]
Guys test it in firefox too please.

**Comment by Thunder-Blaze** [comment]
> Guys test it in firefox too please.

Sure I'll test in about 1 or 2 hr 👍🏻

**Comment by prem-k-r** [comment]
Why lol.. we are pushing this in chrome store branch

**Comment by itz-rj-here** [comment]
> Why lol.. we are pushing this in chrome store branch 

Wait i forgot bruh 🗿

**Comment by Thunder-Blaze** [comment]
> Why lol.. we are pushing this in chrome store branch

Because quotes are not in main branch?

**Comment by itz-rj-here** [comment]
> > Why lol.. we are pushing this in chrome store branch
> 
> Because quotes are not in main branch?

Nope i just realized it.

**Comment by Thunder-Blaze** [comment]
> Guys test it in firefox too please.

It's working 👍🏻

File: quotes.js [hunk 5]
```diff
@@ -1,35 +1,120 @@
...
+const authorName = document.querySelector('.authorName span');
 
-async function fetchAndDisplayQuote() {
-    try {
-        const response = await fetch(apiUrl);
-        const data = await response.json();
-        const quotes = JSON.parse(data.contents);
+// Set character limits for quotes
+const MIN_QUOTE_LENGTH = 90;
+const MAX_QUOTE_LENGTH = 145;
```
Comment (prem-k-r) [inline quotes.js:7]: um.. let's keep it 140.. got an overflowing quote :(

**Review by prem-k-r — DISMISSED** [review]

**Comment by prem-k-r** [comment]
Please change feedback tg link
```
https://t.me/Material_You_NewTab
```
https://github.com/XengShi/materialYouNewTab/pull/413/commits/3dd676c1672762ecfb25f6a5b2a0b40ec51f8f35

**Comment by itz-rj-here** [comment]
> Please change feedback tg link
> ```
> https://t.me/Material_You_NewTab
> ```
> https://github.com/XengShi/materialYouNewTab/pull/413/commits/3dd676c1672762ecfb25f6a5b2a0b40ec51f8f35

You do. I don’t want anymore changes here. Everything here is good to go for now.

File: quotes.js [hunk 6]
```diff
@@ -1,35 +1,120 @@
-const apiUrl = "https://api.allorigins.win/get?url=" + encodeURIComponent("https://zenquotes.io/api/quotes/");
+const apiUrl = "https://dummyjson.com/quotes?limit=50";
```
Comment (Shacklebolt13) [inline quotes.js:1]: I would suggest an alternative approach to this: 

1. Method 1:
 a. Fetch only 1 quote for faster response with `https://dummyjson.com/quotes?limit=1`. This would give you the total size. (say 1000). This can be cached permanently or made a cookie to be refreshed every 10 days or so. 
 b. Generate a random number between 1 and 1000. (say 201)
 c. Fetch the specific quote with `https://dummyjson.com/quotes/201/`
  
  challenges: 
       1.  can't filter quote size. It would have to be handled by increasing component height or something. 
       
3. Method 2:
 a. Fetch all the quotes at once with `https://dummyjson.com/quotes?limit=0` and cache to be refreshed every 10 days or so.
 b. filter quotes if required before storing. 
 c. show quote from this cache instead of API calls each time.

Open to modifications as per the owner's requirements, @XengShi

Comment (Thunder-Blaze) [reply quotes.js:1]: Wouldn't this highly increase the local storage usage ?

Though if it doesn't affect performance then ig it's a good idea

Comment (prem-k-r) [reply quotes.js:1]: nice ideas Gagandeep :)

Comment (prem-k-r) [reply quotes.js:1]: > For method 2, Wouldn't this highly increase the local storage usage ?

we may use indexeddb.

**Comment by XengShi** [comment]
This is nice and works fine, but it shows some overly religious quotes, which might not suit users who are atheists or from different religions. @itz-rj-here

**Comment by itz-rj-here** [comment]
> This is nice and works fine, but it shows some overly religious quotes, which might not suit users who are atheists or from different religions. @itz-rj-here

I can understand then let me look into some other quotes if i could find...
thanks.

File: quotes.js (hunk 6 above)
Comment (Thunder-Blaze) [reply quotes.js:1]: If we are storing all of them
why we even need API ?
lets just create a json of about 500 quotes fetched from some api and then filtered by someone inside quotes.js ?

though Idk how it'll impact performance or other things

**Comment by prem-k-r** [comment]
@itz-rj-here `Closes #issue` is not automatically closing issues anymore, maybe rules are restricting it?

**Comment by itz-rj-here** [comment]
> @itz-rj-here `Closes #issue` is not automatically closing issues anymore, maybe rules are restricting it? 

For collaborators we have to use the development settings at the right and add the issues on it. Then it will work as you want. But the closes command will work properly for others.

**Comment by prem-k-r** [comment]
Ohk
